
var AWS = require("aws-sdk");
var async = require("async");

AWS.config = new AWS.Config();
AWS.config.accessKeyId = process.env.AWS_ID;
AWS.config.secretAccessKey = process.env.AWS_Key;
AWS.config.region = "us-east-2";

var dynamodb = new AWS.DynamoDB();

var diaryEntries = [
   {
      "pk":{
         "N":"0"
      },
      "date":{
         "N":"10042018"
      },
      "time":{
         "N":"1831"
      },
      "latlon":{
         "NS":[
            "40.7118201",
            "-73.9737431"
         ]
      },
      "price":{
         "N":"7"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Bud Light"
      }
   },
   {
      "pk":{
         "N":"1"
      },
      "date":{
         "N":"10042018"
      },
      "time":{
         "N":"1904"
      },
      "latlon":{
         "NS":[
            "40.7118201",
            "-73.9572489"
         ]
      },
      "price":{
         "N":"7"
      },
      "drinkFm":{
         "S":"tall"
      },
      "liquor":{
         "S":"tequila"
      },
      "brand":{
         "S":"unknown"
      }
   },
   {
      "pk":{
         "N":"2"
      },
      "date":{
         "N":"10042018"
      },
      "time":{
         "N":"2008"
      },
      "latlon":{
         "NS":[
            "40.7118201",
            "-73.9572489"
         ]
      },
      "price":{
         "N":"7"
      },
      "drinkFm":{
         "S":"tall"
      },
      "liquor":{
         "S":"tequila"
      },
      "brand":{
         "S":"unknown"
      }
   },
   {
      "pk":{
         "N":"3"
      },
      "date":{
         "N":"10042018"
      },
      "time":{
         "N":"2122"
      },
      "latlon":{
         "NS":[
            "40.713089",
            "-73.9573015"
         ]
      },
      "price":{
         "N":"14"
      },
      "drinkFm":{
         "S":"wine glass"
      },
      "liquor":{
         "S":"wine"
      },
      "brand":{
         "S":"Cellar Escoda-Sanahuja"
      }
   },
   {
      "pk":{
         "N":"4"
      },
      "date":{
         "N":"10042018"
      },
      "time":{
         "N":"2342"
      },
      "latlon":{
         "NS":[
            "40.7125548",
            "-73.9558347"
         ]
      },
      "price":{
         "N":"8"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Brooklyn Lager"
      }
   },
   {
      "pk":{
         "N":"5"
      },
      "date":{
         "N":"10112018"
      },
      "time":{
         "N":"1917"
      },
      "latlon":{
         "NS":[
            "40.7294657",
            "-73.9872883"
         ]
      },
      "price":{
         "N":"4"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Sam Adams"
      }
   },
   {
      "pk":{
         "N":"6"
      },
      "date":{
         "N":"10112018"
      },
      "time":{
         "N":"2002"
      },
      "latlon":{
         "NS":[
            "40.7294657",
            "-73.9872883"
         ]
      },
      "price":{
         "N":"4"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Sam Adams"
      }
   },
   {
      "pk":{
         "N":"7"
      },
      "date":{
         "N":"10112018"
      },
      "time":{
         "N":"2033"
      },
      "latlon":{
         "NS":[
            "40.7294657",
            "-73.9872883"
         ]
      },
      "price":{
         "N":"4"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Sam Adams"
      }
   },
   {
      "pk":{
         "N":"8"
      },
      "date":{
         "N":"10112018"
      },
      "time":{
         "N":"2115"
      },
      "latlon":{
         "NS":[
            "40.7294657",
            "-73.9872883"
         ]
      },
      "price":{
         "N":"4"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Bud Light"
      }
   },
   {
      "pk":{
         "N":"9"
      },
      "date":{
         "N":"10122018"
      },
      "time":{
         "N":"2127"
      },
      "latlon":{
         "NS":[
            "40.7366896",
            "-73.991439"
         ]
      },
      "price":{
         "N":"7"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Negra Modelo"
      }
   },
   {
      "pk":{
         "N":"10"
      },
      "date":{
         "N":"10122018"
      },
      "time":{
         "N":"2240"
      },
      "latlon":{
         "NS":[
            "40.7366896",
            "-73.991439"
         ]
      },
      "price":{
         "N":"7"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Stella Artois"
      }
   },
   {
      "pk":{
         "N":"11"
      },
      "date":{
         "N":"10122018"
      },
      "time":{
         "N":"2342"
      },
      "latlon":{
         "NS":[
            "40.7112767",
            "-73.9578983"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Flat Tire"
      }
   },
   {
      "pk":{
         "N":"12"
      },
      "date":{
         "N":"10132018"
      },
      "time":{
         "N":"1923"
      },
      "latlon":{
         "NS":[
            "40.698921",
            "-73.974845"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Flat Tire"
      }
   },
   {
      "pk":{
         "N":"13"
      },
      "date":{
         "N":"10132018"
      },
      "time":{
         "N":"2142"
      },
      "latlon":{
         "NS":[
            "40.6990443",
            "-73.9745337"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"wine glass"
      },
      "liquor":{
         "S":"wine"
      },
      "brand":{
         "S":"Unknown"
      }
   },
   {
      "pk":{
         "N":"14"
      },
      "date":{
         "N":"10132018"
      },
      "time":{
         "N":"2238"
      },
      "latlon":{
         "NS":[
            "40.698921",
            "-73.974845"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Brooklyn Lager"
      }
   },
   {
      "pk":{
         "N":"15"
      },
      "date":{
         "N":"10142018"
      },
      "time":{
         "N":"15"
      },
      "latlon":{
         "NS":[
            "40.7370996",
            "-73.9737431"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"cup"
      },
      "liquor":{
         "S":"gin"
      },
      "brand":{
         "S":"Gordons"
      }
   },
   {
      "pk":{
         "N":"16"
      },
      "date":{
         "N":"10142018"
      },
      "time":{
         "N":"46"
      },
      "latlon":{
         "NS":[
            "40.7370996",
            "-73.9737431"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Corona"
      }
   },
   {
      "pk":{
         "N":"17"
      },
      "date":{
         "N":"10142018"
      },
      "time":{
         "N":"45"
      },
      "latlon":{
         "NS":[
            "40.7370996",
            "-73.9737431"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"shot"
      },
      "liquor":{
         "S":"aguardiente"
      },
      "brand":{
         "S":"Nectar"
      }
   },
   {
      "pk":{
         "N":"18"
      },
      "date":{
         "N":"10142018"
      },
      "time":{
         "N":"139"
      },
      "latlon":{
         "NS":[
            "40.7294657",
            "-73.9872883"
         ]
      },
      "price":{
         "N":"7"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Lagunitas"
      }
   },
   {
      "pk":{
         "N":"19"
      },
      "date":{
         "N":"10142018"
      },
      "time":{
         "N":"229"
      },
      "latlon":{
         "NS":[
            "40.7294657",
            "-73.9872883"
         ]
      },
      "price":{
         "N":"7"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Lagunitas"
      }
   },
   {
      "pk":{
         "N":"20"
      },
      "date":{
         "N":"10152018"
      },
      "time":{
         "N":"2237"
      },
      "latlon":{
         "NS":[
            "40.7090847",
            "-73.9526479"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"short glass"
      },
      "liquor":{
         "S":"rum"
      },
      "brand":{
         "S":"Santa Fe"
      }
   },
   {
      "pk":{
         "N":"21"
      },
      "date":{
         "N":"10192018"
      },
      "time":{
         "N":"1904"
      },
      "latlon":{
         "NS":[
            "40.7225556",
            "-73.9864347"
         ]
      },
      "price":{
         "N":"10"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"unknown"
      }
   },
   {
      "pk":{
         "N":"22"
      },
      "date":{
         "N":"10192018"
      },
      "time":{
         "N":"1944"
      },
      "latlon":{
         "NS":[
            "40.7225556",
            "-73.9864347"
         ]
      },
      "price":{
         "N":"7"
      },
      "drinkFm":{
         "S":"shot"
      },
      "liquor":{
         "S":"jagermeister"
      },
      "brand":{
         "S":"Jagermeister"
      }
   },
   {
      "pk":{
         "N":"23"
      },
      "date":{
         "N":"10192018"
      },
      "time":{
         "N":"2002"
      },
      "latlon":{
         "NS":[
            "40.7225556",
            "-73.9864347"
         ]
      },
      "price":{
         "N":"10"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"unknown"
      }
   },
   {
      "pk":{
         "N":"24"
      },
      "date":{
         "N":"10192018"
      },
      "time":{
         "N":"2052"
      },
      "latlon":{
         "NS":[
            "40.7225556",
            "-73.9864347"
         ]
      },
      "price":{
         "N":"10"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"unknown"
      }
   },
   {
      "pk":{
         "N":"25"
      },
      "date":{
         "N":"10192018"
      },
      "time":{
         "N":"2138"
      },
      "latlon":{
         "NS":[
            "40.7225556",
            "-73.9864347"
         ]
      },
      "price":{
         "N":"10"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"unknown"
      }
   },
   {
      "pk":{
         "N":"26"
      },
      "date":{
         "N":"10202018"
      },
      "time":{
         "N":"75"
      },
      "latlon":{
         "NS":[
            "40.7225556",
            "-73.9864347"
         ]
      },
      "price":{
         "N":"5"
      },
      "drinkFm":{
         "S":"can"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Pabst Blue Ribbon"
      }
   },
   {
      "pk":{
         "N":"27"
      },
      "date":{
         "N":"10202018"
      },
      "time":{
         "N":"2022"
      },
      "latlon":{
         "NS":[
            "40.7521944",
            "-73.9853695"
         ]
      },
      "price":{
         "N":"14"
      },
      "drinkFm":{
         "S":"short glass"
      },
      "liquor":{
         "S":"bourbon"
      },
      "brand":{
         "S":"Bulleit"
      }
   },
   {
      "pk":{
         "N":"28"
      },
      "date":{
         "N":"10212018"
      },
      "time":{
         "N":"1718"
      },
      "latlon":{
         "NS":[
            "40.7112767",
            "-73.9578983"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"champagne glass"
      },
      "liquor":{
         "S":"sparkling wine"
      },
      "brand":{
         "S":"unknown"
      }
   },
   {
      "pk":{
         "N":"29"
      },
      "date":{
         "N":"10212018"
      },
      "time":{
         "N":"1739"
      },
      "latlon":{
         "NS":[
            "40.7112767",
            "-73.9578983"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"champagne glass"
      },
      "liquor":{
         "S":"sparkling wine"
      },
      "brand":{
         "S":"unknown"
      }
   },
   {
      "pk":{
         "N":"30"
      },
      "date":{
         "N":"10212018"
      },
      "time":{
         "N":"1812"
      },
      "latlon":{
         "NS":[
            "40.7112767",
            "-73.9578983"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"champagne glass"
      },
      "liquor":{
         "S":"sparkling wine"
      },
      "brand":{
         "S":"unknown"
      }
   },
   {
      "pk":{
         "N":"31"
      },
      "date":{
         "N":"10212018"
      },
      "time":{
         "N":"1840"
      },
      "latlon":{
         "NS":[
            "40.7112767",
            "-73.9578983"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"champagne glass"
      },
      "liquor":{
         "S":"sparkling wine"
      },
      "brand":{
         "S":"unknown"
      }
   },
   {
      "pk":{
         "N":"32"
      },
      "date":{
         "N":"10262018"
      },
      "time":{
         "N":"2034"
      },
      "latlon":{
         "NS":[
            "40.7112767",
            "-73.9578983"
         ]
      },
      "price":{
         "N":"5"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Stella Artois"
      }
   },
   {
      "pk":{
         "N":"33"
      },
      "date":{
         "N":"10262018"
      },
      "time":{
         "N":"2103"
      },
      "latlon":{
         "NS":[
            "40.7112767",
            "-73.9578983"
         ]
      },
      "price":{
         "N":"5"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Stella Artois"
      }
   },
   {
      "pk":{
         "N":"34"
      },
      "date":{
         "N":"10262018"
      },
      "time":{
         "N":"2126"
      },
      "latlon":{
         "NS":[
            "40.7112767",
            "-73.9578983"
         ]
      },
      "price":{
         "N":"5"
      },
      "drinkFm":{
         "S":"beer"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Stella Artois"
      }
   },
   {
      "pk":{
         "N":"35"
      },
      "date":{
         "N":"10262018"
      },
      "time":{
         "N":"2207"
      },
      "latlon":{
         "NS":[
            "40.7112767",
            "-73.9578983"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"cup"
      },
      "liquor":{
         "S":"gin"
      },
      "brand":{
         "S":"Gordons"
      }
   },
   {
      "pk":{
         "N":"36"
      },
      "date":{
         "N":"10262018"
      },
      "time":{
         "N":"2347"
      },
      "latlon":{
         "NS":[
            "40.6969513",
            "-73.9345859"
         ]
      },
      "price":{
         "N":"14"
      },
      "drinkFm":{
         "S":"cup"
      },
      "liquor":{
         "S":"whiskey"
      },
      "brand":{
         "S":"unknown"
      }
   },
   {
      "pk":{
         "N":"37"
      },
      "date":{
         "N":"10272018"
      },
      "time":{
         "N":"20"
      },
      "latlon":{
         "NS":[
            "40.6969513",
            "-73.9345859"
         ]
      },
      "price":{
         "N":"14"
      },
      "drinkFm":{
         "S":"cup"
      },
      "liquor":{
         "S":"whiskey"
      },
      "brand":{
         "S":"unknown"
      }
   },
   {
      "pk":{
         "N":"38"
      },
      "date":{
         "N":"10272018"
      },
      "time":{
         "N":"83"
      },
      "latlon":{
         "NS":[
            "40.6969513",
            "-73.9345859"
         ]
      },
      "price":{
         "N":"14"
      },
      "drinkFm":{
         "S":"cup"
      },
      "liquor":{
         "S":"whiskey"
      },
      "brand":{
         "S":"unknown"
      }
   },
   {
      "pk":{
         "N":"39"
      },
      "date":{
         "N":"10272018"
      },
      "time":{
         "N":"2244"
      },
      "latlon":{
         "NS":[
            "40.6718819",
            "-73.951413"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"bottle"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"unknown"
      }
   },
   {
      "pk":{
         "N":"40"
      },
      "date":{
         "N":"10272018"
      },
      "time":{
         "N":"2343"
      },
      "latlon":{
         "NS":[
            "40.6718819",
            "-73.951413"
         ]
      },
      "price":{
         "N":"2.75"
      },
      "drinkFm":{
         "S":"bottle"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Shocktop"
      }
   },
   {
      "pk":{
         "N":"41"
      },
      "date":{
         "N":"10272018"
      },
      "time":{
         "N":"11"
      },
      "latlon":{
         "NS":[
            "40.6718819",
            "-73.951413"
         ]
      },
      "price":{
         "N":"2.75"
      },
      "drinkFm":{
         "S":"bottle"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Shocktop"
      }
   },
   {
      "pk":{
         "N":"42"
      },
      "date":{
         "N":"10272018"
      },
      "time":{
         "N":"25"
      },
      "latlon":{
         "NS":[
            "40.6718819",
            "-73.951413"
         ]
      },
      "price":{
         "N":"2.75"
      },
      "drinkFm":{
         "S":"bottle"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Shocktop"
      }
   },
   {
      "pk":{
         "N":"43"
      },
      "date":{
         "N":"10272018"
      },
      "time":{
         "N":"96"
      },
      "latlon":{
         "NS":[
            "40.6718819",
            "-73.951413"
         ]
      },
      "price":{
         "N":"2.75"
      },
      "drinkFm":{
         "S":"bottle"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Shocktop"
      }
   },
   {
      "pk":{
         "N":"44"
      },
      "date":{
         "N":"10272018"
      },
      "time":{
         "N":"140"
      },
      "latlon":{
         "NS":[
            "40.6718819",
            "-73.951413"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"cup"
      },
      "liquor":{
         "S":"various"
      },
      "brand":{
         "S":"unknown"
      }
   },
   {
      "pk":{
         "N":"45"
      },
      "date":{
         "N":"10312018"
      },
      "time":{
         "N":"2214"
      },
      "latlon":{
         "NS":[
            "40.737034",
            "-73.992245"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"bottle"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Stella Artois"
      }
   },
   {
      "pk":{
         "N":"46"
      },
      "date":{
         "N":"11012018"
      },
      "time":{
         "N":"2233"
      },
      "latlon":{
         "NS":[
            "40.7170393",
            "-73.9973807"
         ]
      },
      "price":{
         "N":"6"
      },
      "drinkFm":{
         "S":"cup"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Blue Moon"
      }
   },
   {
      "pk":{
         "N":"47"
      },
      "date":{
         "N":"11012018"
      },
      "time":{
         "N":"2258"
      },
      "latlon":{
         "NS":[
            "40.7170393",
            "-73.9973807"
         ]
      },
      "price":{
         "N":"6"
      },
      "drinkFm":{
         "S":"cup"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Blue Moon"
      }
   },
   {
      "pk":{
         "N":"48"
      },
      "date":{
         "N":"11012018"
      },
      "time":{
         "N":"2320"
      },
      "latlon":{
         "NS":[
            "40.7170393",
            "-73.9973807"
         ]
      },
      "price":{
         "N":"6"
      },
      "drinkFm":{
         "S":"cup"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Blue Moon"
      }
   },
   {
      "pk":{
         "N":"49"
      },
      "date":{
         "N":"11012018"
      },
      "time":{
         "N":"2359"
      },
      "latlon":{
         "NS":[
            "40.7170393",
            "-73.9973807"
         ]
      },
      "price":{
         "N":"6"
      },
      "drinkFm":{
         "S":"cup"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Brooklyn Lager"
      }
   },
   {
      "pk":{
         "N":"50"
      },
      "date":{
         "N":"11092018"
      },
      "time":{
         "N":"2237"
      },
      "latlon":{
         "NS":[
            "40.7615582",
            "-73.982604"
         ]
      },
      "price":{
         "N":"4.5"
      },
      "drinkFm":{
         "S":"bottle"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Heineiken"
      }
   },
   {
      "pk":{
         "N":"51"
      },
      "date":{
         "N":"11092018"
      },
      "time":{
         "N":"2303"
      },
      "latlon":{
         "NS":[
            "40.7615582",
            "-73.982604"
         ]
      },
      "price":{
         "N":"4.5"
      },
      "drinkFm":{
         "S":"bottle"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Heineiken"
      }
   },
   {
      "pk":{
         "N":"52"
      },
      "date":{
         "N":"11092018"
      },
      "time":{
         "N":"2325"
      },
      "latlon":{
         "NS":[
            "40.7615582",
            "-73.982604"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"shot"
      },
      "liquor":{
         "S":"tequila"
      },
      "brand":{
         "S":"Jose Cuervo"
      }
   },
   {
      "pk":{
         "N":"53"
      },
      "date":{
         "N":"11092018"
      },
      "time":{
         "N":"2327"
      },
      "latlon":{
         "NS":[
            "40.7615582",
            "-73.982604"
         ]
      },
      "price":{
         "N":"4.5"
      },
      "drinkFm":{
         "S":"bottle"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Heineiken"
      }
   },
   {
      "pk":{
         "N":"54"
      },
      "date":{
         "N":"11092018"
      },
      "time":{
         "N":"2353"
      },
      "latlon":{
         "NS":[
            "40.7615582",
            "-73.982604"
         ]
      },
      "price":{
         "N":"4.5"
      },
      "drinkFm":{
         "S":"bottle"
      },
      "liquor":{
         "S":"beer"
      },
      "brand":{
         "S":"Heineiken"
      }
   },
   {
      "pk":{
         "N":"55"
      },
      "date":{
         "N":"11102018"
      },
      "time":{
         "N":"28"
      },
      "latlon":{
         "NS":[
            "40.7615582",
            "-73.982604"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"shot"
      },
      "liquor":{
         "S":"aguardiente"
      },
      "brand":{
         "S":"Nectar"
      }
   },
   {
      "pk":{
         "N":"56"
      },
      "date":{
         "N":"11102018"
      },
      "time":{
         "N":"66"
      },
      "latlon":{
         "NS":[
            "40.7615582",
            "-73.982604"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"shot"
      },
      "liquor":{
         "S":"tequila"
      },
      "brand":{
         "S":"Jose Cuervo"
      }
   },
   {
      "pk":{
         "N":"57"
      },
      "date":{
         "N":"11102018"
      },
      "time":{
         "N":"144"
      },
      "latlon":{
         "NS":[
            "40.7262099",
            "-73.9858099"
         ]
      },
      "price":{
         "N":"14"
      },
      "drinkFm":{
         "S":"tall glass"
      },
      "liquor":{
         "S":"tequila"
      },
      "brand":{
         "S":"unknown"
      }
   },
   {
      "pk":{
         "N":"58"
      },
      "date":{
         "N":"11102018"
      },
      "time":{
         "N":"165"
      },
      "latlon":{
         "NS":[
            "40.7262099",
            "-73.9858099"
         ]
      },
      "price":{
         "N":"0"
      },
      "drinkFm":{
         "S":"tall glass"
      },
      "liquor":{
         "S":"tequila"
      },
      "brand":{
         "S":"unknown"
      }
   }
];

// console.log(diaryEntries)
var counter = 0

async.eachSeries(diaryEntries, function(value, callback) {
        var params = {};
        console.log(counter)
        
       console.log(value);
        params.Item = value;
        params.TableName = "deardiary";

        dynamodb.putItem(params, function (err, data) {
          if (err) console.log('ERROR'); // an error occurred
          else     console.log(data);           // successful response
        });
    setTimeout(callback, 2000);
    counter = counter + 1
}); 